# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=250)),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good_description', models.TextField()),
                ('good_code', models.CharField(max_length=200)),
                ('good_country', models.CharField(max_length=150, null=True)),
                ('good_article', models.CharField(max_length=200, null=True)),
                ('good_size', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250)),
                ('group_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Good')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Good'),
        ),
    ]
