# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160124_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Group', verbose_name='Группа'),
        ),
    ]
