# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160131_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_image',
            field=models.ImageField(null=True, upload_to='goods_img', verbose_name='Кртинка'),
        ),
    ]
